

// PLAYER
const PLAYER_SPEED = 350    
const PLAYER_JUMP = 460

// JEU 
const GAME_HEIGHT = 448
const GAME_WIDTH = 896
const GAME_GRAVITY = 1100

// SET DEPTH
const CHRONO_LAYER_DEPTH = 100
const PLAYER_LAYER_DEPTH = 80
const TWEEN_MOUVEMENT = 65
const REPOSE_TWEEN_LAYER_DEPTH = 60
const FIN_LAYER_DEPTH = 55
const DEBUT_LAYER_DEPTH = 50
const SOLIDE_LAYER_DEPTH = 40
const OBSTACLE_LAYER_DEPTH = 30
const ARRIERE_LAYER_DEPTH = 20
const BACKGROUND_LAYER_DEPTH = 10
